### ISSUE TITLE
Open 5D chess discord invite

### ISSUE THREAD

**Issue by Alexbay218** [ThePerkinrex/5dchess#1]
I'm the lead developer of https://chessin5d.net and I'm looking to gather people interested in creating open source projects around 5D chess. Here is the discord link: https://discord.chessin5d.net

There are 5+ different developers on there working on their own projects, so feel free to drop in and say hi.

**Comment by Alexbay218** [comment]
Also surprised you didn't find my 5d chess npm library (https://www.npmjs.com/package/5d-chess-js).

I've also created a PIXI.js based renderer to more easily display / play 5d chess (https://www.npmjs.com/package/5d-chess-renderer) that you might be interested in looking at.

**Comment by ThePerkinrex** [comment]
Well, the project is now a bit dead, but I will surely take a look at it.

And about the npm library, the thing is that I was trying to make it work on some laptops that have chrome 40-something, that's why I use a 4 year old version of p5, and typescript, so that I can still use newer JS features, as well as strong typing.

Anyways, I will check it out, but this was a toy project. Yours looks a lot better and a lot more polished.

**Comment by Alexbay218** [comment]
No worries, even if you'll never work on 5d chess again, the invites always open! A lot of interesting discussion goes on in that server, from reverse engineering the game to bot algorithms! I always do a quick search on github for new 5d chess projects to see if people are interested in joining, since two (or more) minds are better than one!
